[2023-06-09 15:08:45,235] {taskinstance.py:1029} INFO - Dependencies not met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_18.csv scheduled__2023-06-08T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state which is not a valid state for execution. The task must be cleared in order to be run.
[2023-06-09 15:08:45,393] {local_task_job.py:99} INFO - Task is not able to be run
[2023-06-09 15:22:29,564] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_18.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:29,793] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_18.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:29,797] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:29,801] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:29,802] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:30,072] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_18.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:30,102] {standard_task_runner.py:52} INFO - Started process 3575 to run task
[2023-06-09 15:22:30,158] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_18.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpew096l0g', '--error-file', '/tmp/tmptkoyv7ay']
[2023-06-09 15:22:30,185] {standard_task_runner.py:77} INFO - Job 80: Subtask load_sftp_datadata_18.csv
[2023-06-09 15:22:30,695] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_18.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:31,216] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_18.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:31,255] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:31,379] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:31,567] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_18.csv, execution_date=20230609T152024, start_date=20230609T152229, end_date=20230609T152231
[2023-06-09 15:22:32,639] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:50,404] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_18.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:50,652] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_18.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:50,654] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:50,655] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:50,656] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:50,780] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_18.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:50,848] {standard_task_runner.py:52} INFO - Started process 974 to run task
[2023-06-09 16:52:50,884] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_18.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpccow2b2w', '--error-file', '/tmp/tmpbees8nam']
[2023-06-09 16:52:50,922] {standard_task_runner.py:77} INFO - Job 39: Subtask load_sftp_datadata_18.csv
[2023-06-09 16:52:51,359] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_18.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:51,757] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_18.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:51,810] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:51,975] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:52,136] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_18.csv, execution_date=20230608T000000, start_date=20230609T165250, end_date=20230609T165252
[2023-06-09 16:52:53,135] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
