[2023-06-09 14:18:10,960] {processor.py:163} INFO - Started process (PID=271) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:18:10,964] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:18:10,966] {logging_mixin.py:109} INFO - [2023-06-09 14:18:10,966] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:18:11,019] {logging_mixin.py:109} INFO - [2023-06-09 14:18:11,015] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:18:11,047] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:18:11,062] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.108 seconds
[2023-06-09 14:19:08,357] {processor.py:163} INFO - Started process (PID=336) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:19:08,361] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:19:08,363] {logging_mixin.py:109} INFO - [2023-06-09 14:19:08,363] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:19:08,393] {logging_mixin.py:109} INFO - [2023-06-09 14:19:08,387] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:19:08,439] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:19:08,480] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.130 seconds
[2023-06-09 14:19:39,113] {processor.py:163} INFO - Started process (PID=390) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:19:39,118] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:19:39,124] {logging_mixin.py:109} INFO - [2023-06-09 14:19:39,123] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:19:39,188] {logging_mixin.py:109} INFO - [2023-06-09 14:19:39,180] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:19:39,238] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:19:39,257] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.158 seconds
[2023-06-09 14:20:09,896] {processor.py:163} INFO - Started process (PID=457) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:20:09,902] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:20:09,905] {logging_mixin.py:109} INFO - [2023-06-09 14:20:09,905] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:20:09,984] {logging_mixin.py:109} INFO - [2023-06-09 14:20:09,979] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:20:10,022] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:20:10,040] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.156 seconds
[2023-06-09 14:20:40,442] {processor.py:163} INFO - Started process (PID=504) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:20:40,445] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:20:40,448] {logging_mixin.py:109} INFO - [2023-06-09 14:20:40,447] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:20:40,507] {logging_mixin.py:109} INFO - [2023-06-09 14:20:40,496] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:20:40,663] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:20:40,703] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.269 seconds
[2023-06-09 14:21:11,204] {processor.py:163} INFO - Started process (PID=570) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:21:11,209] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:21:11,212] {logging_mixin.py:109} INFO - [2023-06-09 14:21:11,211] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:21:11,249] {logging_mixin.py:109} INFO - [2023-06-09 14:21:11,243] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:21:11,283] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:21:11,299] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.104 seconds
[2023-06-09 14:21:41,746] {processor.py:163} INFO - Started process (PID=617) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:21:41,750] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:21:41,752] {logging_mixin.py:109} INFO - [2023-06-09 14:21:41,752] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:21:41,778] {logging_mixin.py:109} INFO - [2023-06-09 14:21:41,774] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:21:41,808] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:21:41,822] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.083 seconds
[2023-06-09 14:22:12,331] {processor.py:163} INFO - Started process (PID=683) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:22:12,334] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:22:12,337] {logging_mixin.py:109} INFO - [2023-06-09 14:22:12,336] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:22:12,370] {logging_mixin.py:109} INFO - [2023-06-09 14:22:12,366] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:22:12,398] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:22:12,413] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.089 seconds
[2023-06-09 14:22:42,906] {processor.py:163} INFO - Started process (PID=730) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:22:42,910] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:22:42,913] {logging_mixin.py:109} INFO - [2023-06-09 14:22:42,912] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:22:42,945] {logging_mixin.py:109} INFO - [2023-06-09 14:22:42,940] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:22:42,975] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:22:42,990] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.091 seconds
[2023-06-09 14:23:13,553] {processor.py:163} INFO - Started process (PID=796) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:23:13,557] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:23:13,560] {logging_mixin.py:109} INFO - [2023-06-09 14:23:13,559] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:23:13,586] {logging_mixin.py:109} INFO - [2023-06-09 14:23:13,582] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:23:13,616] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:23:13,632] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.086 seconds
[2023-06-09 14:23:44,080] {processor.py:163} INFO - Started process (PID=843) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:23:44,083] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:23:44,085] {logging_mixin.py:109} INFO - [2023-06-09 14:23:44,085] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:23:44,116] {logging_mixin.py:109} INFO - [2023-06-09 14:23:44,112] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:23:44,143] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:23:44,157] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.084 seconds
[2023-06-09 14:24:14,567] {processor.py:163} INFO - Started process (PID=909) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:24:14,570] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:24:14,572] {logging_mixin.py:109} INFO - [2023-06-09 14:24:14,572] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:24:14,597] {logging_mixin.py:109} INFO - [2023-06-09 14:24:14,593] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:24:14,630] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:24:14,646] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.086 seconds
[2023-06-09 14:24:45,119] {processor.py:163} INFO - Started process (PID=956) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:24:45,122] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:24:45,124] {logging_mixin.py:109} INFO - [2023-06-09 14:24:45,124] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:24:45,151] {logging_mixin.py:109} INFO - [2023-06-09 14:24:45,146] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:24:45,178] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:24:45,192] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.080 seconds
[2023-06-09 14:25:15,598] {processor.py:163} INFO - Started process (PID=1022) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:25:15,602] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:25:15,604] {logging_mixin.py:109} INFO - [2023-06-09 14:25:15,604] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:25:15,638] {logging_mixin.py:109} INFO - [2023-06-09 14:25:15,631] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:25:15,670] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:25:15,691] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.102 seconds
[2023-06-09 14:25:46,125] {processor.py:163} INFO - Started process (PID=1079) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:25:46,129] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:25:46,131] {logging_mixin.py:109} INFO - [2023-06-09 14:25:46,131] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:25:46,159] {logging_mixin.py:109} INFO - [2023-06-09 14:25:46,154] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:25:46,189] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:25:46,205] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.087 seconds
[2023-06-09 14:26:16,609] {processor.py:163} INFO - Started process (PID=1135) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:26:16,614] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:26:16,616] {logging_mixin.py:109} INFO - [2023-06-09 14:26:16,616] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:26:16,643] {logging_mixin.py:109} INFO - [2023-06-09 14:26:16,639] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:26:16,671] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:26:16,687] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.084 seconds
[2023-06-09 14:26:47,178] {processor.py:163} INFO - Started process (PID=1190) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:26:47,181] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:26:47,184] {logging_mixin.py:109} INFO - [2023-06-09 14:26:47,183] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:26:47,212] {logging_mixin.py:109} INFO - [2023-06-09 14:26:47,207] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:26:47,242] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:26:47,257] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.086 seconds
[2023-06-09 14:27:17,676] {processor.py:163} INFO - Started process (PID=1238) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:27:17,680] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:27:17,682] {logging_mixin.py:109} INFO - [2023-06-09 14:27:17,681] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:27:17,707] {logging_mixin.py:109} INFO - [2023-06-09 14:27:17,703] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:27:17,736] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:27:17,751] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.080 seconds
[2023-06-09 14:33:38,742] {processor.py:163} INFO - Started process (PID=1285) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:33:38,746] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:33:38,748] {logging_mixin.py:109} INFO - [2023-06-09 14:33:38,748] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:33:38,780] {logging_mixin.py:109} INFO - [2023-06-09 14:33:38,775] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:33:38,811] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:33:38,827] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.094 seconds
[2023-06-09 14:34:09,905] {processor.py:163} INFO - Started process (PID=1351) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:34:09,916] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:34:09,921] {logging_mixin.py:109} INFO - [2023-06-09 14:34:09,920] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:34:09,971] {logging_mixin.py:109} INFO - [2023-06-09 14:34:09,966] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:34:10,030] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:34:10,054] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.157 seconds
[2023-06-09 14:34:40,610] {processor.py:163} INFO - Started process (PID=1401) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:34:40,614] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:34:40,616] {logging_mixin.py:109} INFO - [2023-06-09 14:34:40,615] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:34:40,641] {logging_mixin.py:109} INFO - [2023-06-09 14:34:40,637] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:34:40,667] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:34:40,681] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.077 seconds
[2023-06-09 14:35:11,196] {processor.py:163} INFO - Started process (PID=1467) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:35:11,200] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:35:11,202] {logging_mixin.py:109} INFO - [2023-06-09 14:35:11,202] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:35:11,229] {logging_mixin.py:109} INFO - [2023-06-09 14:35:11,224] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:35:11,255] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:35:11,273] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.084 seconds
[2023-06-09 14:35:41,834] {processor.py:163} INFO - Started process (PID=1514) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:35:41,837] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:35:41,840] {logging_mixin.py:109} INFO - [2023-06-09 14:35:41,839] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:35:41,868] {logging_mixin.py:109} INFO - [2023-06-09 14:35:41,863] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:35:41,902] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:35:41,919] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.092 seconds
[2023-06-09 14:36:12,454] {processor.py:163} INFO - Started process (PID=1580) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:36:12,458] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:36:12,460] {logging_mixin.py:109} INFO - [2023-06-09 14:36:12,460] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:36:12,488] {logging_mixin.py:109} INFO - [2023-06-09 14:36:12,481] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:36:12,516] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:36:12,532] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.084 seconds
[2023-06-09 14:36:43,003] {processor.py:163} INFO - Started process (PID=1627) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:36:43,007] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:36:43,009] {logging_mixin.py:109} INFO - [2023-06-09 14:36:43,008] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:36:43,034] {logging_mixin.py:109} INFO - [2023-06-09 14:36:43,029] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:36:43,062] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:36:43,077] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.080 seconds
[2023-06-09 14:37:13,542] {processor.py:163} INFO - Started process (PID=1693) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:37:13,546] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:37:13,549] {logging_mixin.py:109} INFO - [2023-06-09 14:37:13,549] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:37:13,579] {logging_mixin.py:109} INFO - [2023-06-09 14:37:13,573] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:37:13,609] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:37:13,626] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.092 seconds
[2023-06-09 14:37:43,858] {processor.py:163} INFO - Started process (PID=1740) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:37:43,862] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:37:43,864] {logging_mixin.py:109} INFO - [2023-06-09 14:37:43,864] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:37:43,892] {logging_mixin.py:109} INFO - [2023-06-09 14:37:43,888] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:37:43,922] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:37:43,938] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.088 seconds
[2023-06-09 14:38:14,238] {processor.py:163} INFO - Started process (PID=1805) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:38:14,245] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:38:14,250] {logging_mixin.py:109} INFO - [2023-06-09 14:38:14,249] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:38:14,300] {logging_mixin.py:109} INFO - [2023-06-09 14:38:14,283] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:38:14,361] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:38:14,413] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.187 seconds
[2023-06-09 14:38:44,972] {processor.py:163} INFO - Started process (PID=1852) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:38:44,977] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:38:44,980] {logging_mixin.py:109} INFO - [2023-06-09 14:38:44,980] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:38:45,014] {logging_mixin.py:109} INFO - [2023-06-09 14:38:45,009] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:38:45,048] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:38:45,065] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.103 seconds
[2023-06-09 14:39:15,582] {processor.py:163} INFO - Started process (PID=1918) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:39:15,586] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:39:15,588] {logging_mixin.py:109} INFO - [2023-06-09 14:39:15,588] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:39:15,618] {logging_mixin.py:109} INFO - [2023-06-09 14:39:15,614] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:39:15,651] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:39:15,667] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.093 seconds
[2023-06-09 14:39:46,233] {processor.py:163} INFO - Started process (PID=1965) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:39:46,238] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:39:46,241] {logging_mixin.py:109} INFO - [2023-06-09 14:39:46,241] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:39:46,271] {logging_mixin.py:109} INFO - [2023-06-09 14:39:46,267] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:39:46,307] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:39:46,324] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.100 seconds
[2023-06-09 14:40:16,811] {processor.py:163} INFO - Started process (PID=2031) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:40:16,816] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:40:16,823] {logging_mixin.py:109} INFO - [2023-06-09 14:40:16,822] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:40:16,858] {logging_mixin.py:109} INFO - [2023-06-09 14:40:16,853] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:40:16,888] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:40:16,904] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.100 seconds
[2023-06-09 14:40:47,476] {processor.py:163} INFO - Started process (PID=2088) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:40:47,479] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:40:47,482] {logging_mixin.py:109} INFO - [2023-06-09 14:40:47,481] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:40:47,510] {logging_mixin.py:109} INFO - [2023-06-09 14:40:47,506] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:40:47,536] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:40:47,551] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.082 seconds
[2023-06-09 14:41:18,030] {processor.py:163} INFO - Started process (PID=2135) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:41:18,033] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:41:18,036] {logging_mixin.py:109} INFO - [2023-06-09 14:41:18,035] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:41:18,065] {logging_mixin.py:109} INFO - [2023-06-09 14:41:18,059] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:41:18,106] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:41:18,127] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.104 seconds
[2023-06-09 14:41:48,583] {processor.py:163} INFO - Started process (PID=2198) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:41:48,586] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:41:48,589] {logging_mixin.py:109} INFO - [2023-06-09 14:41:48,588] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:41:48,618] {logging_mixin.py:109} INFO - [2023-06-09 14:41:48,614] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:41:48,646] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:41:48,662] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.086 seconds
[2023-06-09 14:42:19,205] {processor.py:163} INFO - Started process (PID=2248) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:42:19,208] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:42:19,211] {logging_mixin.py:109} INFO - [2023-06-09 14:42:19,210] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:42:19,236] {logging_mixin.py:109} INFO - [2023-06-09 14:42:19,231] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:42:19,265] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:42:19,280] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.082 seconds
[2023-06-09 14:42:49,763] {processor.py:163} INFO - Started process (PID=2311) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:42:49,767] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:42:49,769] {logging_mixin.py:109} INFO - [2023-06-09 14:42:49,769] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:42:49,797] {logging_mixin.py:109} INFO - [2023-06-09 14:42:49,793] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from transfer_utils.extractor import DataExtractor
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:42:49,826] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:42:49,841] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 0.084 seconds
[2023-06-09 14:42:56,062] {processor.py:163} INFO - Started process (PID=2332) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:42:56,069] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:42:56,076] {logging_mixin.py:109} INFO - [2023-06-09 14:42:56,075] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:42:58,559] {logging_mixin.py:109} INFO - [2023-06-09 14:42:58,549] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:42:58,586] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:42:58,602] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.547 seconds
[2023-06-09 14:43:29,193] {processor.py:163} INFO - Started process (PID=2399) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:43:29,197] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:43:29,199] {logging_mixin.py:109} INFO - [2023-06-09 14:43:29,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:43:31,581] {logging_mixin.py:109} INFO - [2023-06-09 14:43:31,563] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:43:31,623] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:43:31,641] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.456 seconds
[2023-06-09 14:44:02,162] {processor.py:163} INFO - Started process (PID=2453) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:44:02,166] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:44:02,168] {logging_mixin.py:109} INFO - [2023-06-09 14:44:02,167] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:44:04,095] {logging_mixin.py:109} INFO - [2023-06-09 14:44:04,085] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:44:04,122] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:44:04,137] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 1.982 seconds
[2023-06-09 14:44:34,695] {processor.py:163} INFO - Started process (PID=2523) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:44:34,699] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:44:34,701] {logging_mixin.py:109} INFO - [2023-06-09 14:44:34,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:44:37,115] {logging_mixin.py:109} INFO - [2023-06-09 14:44:37,098] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:44:37,173] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:44:37,190] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.502 seconds
[2023-06-09 14:45:07,768] {processor.py:163} INFO - Started process (PID=2584) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:45:07,773] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:45:07,776] {logging_mixin.py:109} INFO - [2023-06-09 14:45:07,775] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:45:10,081] {logging_mixin.py:109} INFO - [2023-06-09 14:45:10,070] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:45:10,110] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:45:10,127] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.366 seconds
[2023-06-09 14:45:40,688] {processor.py:163} INFO - Started process (PID=2644) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:45:40,691] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:45:40,694] {logging_mixin.py:109} INFO - [2023-06-09 14:45:40,693] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:45:42,780] {logging_mixin.py:109} INFO - [2023-06-09 14:45:42,771] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:45:42,808] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:45:42,823] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.142 seconds
[2023-06-09 14:46:13,509] {processor.py:163} INFO - Started process (PID=2714) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:46:13,513] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:46:13,515] {logging_mixin.py:109} INFO - [2023-06-09 14:46:13,515] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:46:15,620] {logging_mixin.py:109} INFO - [2023-06-09 14:46:15,611] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:46:15,646] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:46:15,661] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.159 seconds
[2023-06-09 14:46:46,233] {processor.py:163} INFO - Started process (PID=2764) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:46:46,236] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:46:46,239] {logging_mixin.py:109} INFO - [2023-06-09 14:46:46,238] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:46:48,374] {logging_mixin.py:109} INFO - [2023-06-09 14:46:48,361] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:46:48,407] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:46:48,425] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.199 seconds
[2023-06-09 14:47:18,921] {processor.py:163} INFO - Started process (PID=2834) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:47:18,925] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:47:18,930] {logging_mixin.py:109} INFO - [2023-06-09 14:47:18,929] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:47:21,010] {logging_mixin.py:109} INFO - [2023-06-09 14:47:21,000] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:47:21,042] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:47:21,058] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.144 seconds
[2023-06-09 14:47:51,554] {processor.py:163} INFO - Started process (PID=2904) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:47:51,557] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:47:51,560] {logging_mixin.py:109} INFO - [2023-06-09 14:47:51,559] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:47:53,517] {logging_mixin.py:109} INFO - [2023-06-09 14:47:53,504] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:47:53,549] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:47:53,571] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.024 seconds
[2023-06-09 14:48:24,146] {processor.py:163} INFO - Started process (PID=2955) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:48:24,151] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:48:24,153] {logging_mixin.py:109} INFO - [2023-06-09 14:48:24,153] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:48:26,127] {logging_mixin.py:109} INFO - [2023-06-09 14:48:26,116] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:48:26,160] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:48:26,175] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.036 seconds
[2023-06-09 14:48:56,824] {processor.py:163} INFO - Started process (PID=3025) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:48:56,828] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:48:56,830] {logging_mixin.py:109} INFO - [2023-06-09 14:48:56,830] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:48:58,934] {logging_mixin.py:109} INFO - [2023-06-09 14:48:58,920] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:48:58,966] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:48:58,983] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.167 seconds
[2023-06-09 14:49:29,620] {processor.py:163} INFO - Started process (PID=3092) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:49:29,624] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:49:29,626] {logging_mixin.py:109} INFO - [2023-06-09 14:49:29,626] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:49:33,397] {logging_mixin.py:109} INFO - [2023-06-09 14:49:33,385] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:49:33,427] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:49:33,468] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 3.857 seconds
[2023-06-09 14:50:04,040] {processor.py:163} INFO - Started process (PID=3145) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:50:04,043] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:50:04,045] {logging_mixin.py:109} INFO - [2023-06-09 14:50:04,045] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:50:05,999] {logging_mixin.py:109} INFO - [2023-06-09 14:50:05,990] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:50:06,027] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:50:06,041] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.008 seconds
[2023-06-09 14:50:36,546] {processor.py:163} INFO - Started process (PID=3215) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:50:36,550] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:50:36,553] {logging_mixin.py:109} INFO - [2023-06-09 14:50:36,552] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:50:38,582] {logging_mixin.py:109} INFO - [2023-06-09 14:50:38,569] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:50:38,611] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:50:38,626] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.089 seconds
[2023-06-09 14:51:09,324] {processor.py:163} INFO - Started process (PID=3282) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:51:09,328] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:51:09,331] {logging_mixin.py:109} INFO - [2023-06-09 14:51:09,330] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:51:11,407] {logging_mixin.py:109} INFO - [2023-06-09 14:51:11,397] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:51:11,438] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:51:11,452] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.135 seconds
[2023-06-09 14:51:41,895] {processor.py:163} INFO - Started process (PID=3336) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:51:41,899] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:51:41,902] {logging_mixin.py:109} INFO - [2023-06-09 14:51:41,901] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:51:43,930] {logging_mixin.py:109} INFO - [2023-06-09 14:51:43,920] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:51:43,961] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:51:43,978] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.090 seconds
[2023-06-09 14:52:14,565] {processor.py:163} INFO - Started process (PID=3406) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:52:14,569] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:52:14,571] {logging_mixin.py:109} INFO - [2023-06-09 14:52:14,571] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:52:16,860] {logging_mixin.py:109} INFO - [2023-06-09 14:52:16,850] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:52:16,898] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:52:16,918] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.361 seconds
[2023-06-09 14:52:47,628] {processor.py:163} INFO - Started process (PID=3466) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:52:47,635] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:52:47,639] {logging_mixin.py:109} INFO - [2023-06-09 14:52:47,638] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:52:50,785] {logging_mixin.py:109} INFO - [2023-06-09 14:52:50,773] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:52:50,846] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:52:50,899] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 3.284 seconds
[2023-06-09 14:53:21,549] {processor.py:163} INFO - Started process (PID=3526) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:53:21,553] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:53:21,556] {logging_mixin.py:109} INFO - [2023-06-09 14:53:21,556] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:53:23,486] {logging_mixin.py:109} INFO - [2023-06-09 14:53:23,476] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:53:23,516] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:53:23,534] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 1.994 seconds
[2023-06-09 14:53:54,311] {processor.py:163} INFO - Started process (PID=3596) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:53:54,316] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:53:54,319] {logging_mixin.py:109} INFO - [2023-06-09 14:53:54,318] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:53:56,592] {logging_mixin.py:109} INFO - [2023-06-09 14:53:56,580] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:53:56,622] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:53:56,637] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.336 seconds
[2023-06-09 14:54:27,315] {processor.py:163} INFO - Started process (PID=3656) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:54:27,319] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:54:27,321] {logging_mixin.py:109} INFO - [2023-06-09 14:54:27,321] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:54:29,294] {logging_mixin.py:109} INFO - [2023-06-09 14:54:29,284] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:54:29,326] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:54:29,343] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.034 seconds
[2023-06-09 14:54:59,961] {processor.py:163} INFO - Started process (PID=3716) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:54:59,964] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:54:59,967] {logging_mixin.py:109} INFO - [2023-06-09 14:54:59,966] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:55:01,872] {logging_mixin.py:109} INFO - [2023-06-09 14:55:01,856] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:55:01,902] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:55:01,917] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 1.963 seconds
[2023-06-09 14:55:32,509] {processor.py:163} INFO - Started process (PID=3786) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:55:32,513] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:55:32,515] {logging_mixin.py:109} INFO - [2023-06-09 14:55:32,514] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:55:34,500] {logging_mixin.py:109} INFO - [2023-06-09 14:55:34,489] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:55:34,532] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:55:34,548] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.045 seconds
[2023-06-09 14:56:05,214] {processor.py:163} INFO - Started process (PID=3837) to work on /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:56:05,218] {processor.py:620} INFO - Processing file /opt/airflow/dags/sftps_data_extract.py for tasks to queue
[2023-06-09 14:56:05,221] {logging_mixin.py:109} INFO - [2023-06-09 14:56:05,220] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:56:07,194] {logging_mixin.py:109} INFO - [2023-06-09 14:56:07,182] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sftps_data_extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sftps_data_extract.py", line 13, in <module>
    from extractor import DataExtractor
  File "../transfer_utils/extractor.py", line 4, in <module>
    from transfer_utils.logger import *
ModuleNotFoundError: No module named 'transfer_utils'
[2023-06-09 14:56:07,226] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sftps_data_extract.py
[2023-06-09 14:56:07,241] {processor.py:171} INFO - Processing /opt/airflow/dags/sftps_data_extract.py took 2.036 seconds
