[2023-06-09 15:08:47,266] {taskinstance.py:1029} INFO - Dependencies not met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_3.csv scheduled__2023-06-08T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state which is not a valid state for execution. The task must be cleared in order to be run.
[2023-06-09 15:08:47,373] {local_task_job.py:99} INFO - Task is not able to be run
[2023-06-09 15:22:16,405] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_3.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:16,667] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_3.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:16,670] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:16,673] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:16,680] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:16,820] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_3.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:16,844] {standard_task_runner.py:52} INFO - Started process 3466 to run task
[2023-06-09 15:22:16,876] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_3.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpkjk678tp', '--error-file', '/tmp/tmpfaorr87d']
[2023-06-09 15:22:16,914] {standard_task_runner.py:77} INFO - Job 72: Subtask load_sftp_datadata_3.csv
[2023-06-09 15:22:17,303] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_3.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:17,543] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_3.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:17,585] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:17,771] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:17,946] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_3.csv, execution_date=20230609T152024, start_date=20230609T152216, end_date=20230609T152217
[2023-06-09 15:22:21,684] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:48,648] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_3.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:48,813] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_3.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:48,814] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:48,819] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:48,820] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:48,955] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_3.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:48,991] {standard_task_runner.py:52} INFO - Started process 955 to run task
[2023-06-09 16:52:49,032] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_3.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpp6x50hr3', '--error-file', '/tmp/tmpu72n02f0']
[2023-06-09 16:52:49,101] {standard_task_runner.py:77} INFO - Job 36: Subtask load_sftp_datadata_3.csv
[2023-06-09 16:52:49,417] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_3.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:49,679] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_3.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:49,720] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:49,826] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:50,069] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_3.csv, execution_date=20230608T000000, start_date=20230609T165248, end_date=20230609T165250
[2023-06-09 16:52:50,734] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
