[2023-06-09 15:08:47,010] {taskinstance.py:1029} INFO - Dependencies not met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_19.csv scheduled__2023-06-08T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state which is not a valid state for execution. The task must be cleared in order to be run.
[2023-06-09 15:08:47,249] {local_task_job.py:99} INFO - Task is not able to be run
[2023-06-09 15:22:20,558] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_19.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:21,015] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_19.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:21,020] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:21,022] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:21,024] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:21,218] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_19.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:21,282] {standard_task_runner.py:52} INFO - Started process 3529 to run task
[2023-06-09 15:22:21,280] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_19.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpui8i_xkm', '--error-file', '/tmp/tmphah0d7ge']
[2023-06-09 15:22:21,338] {standard_task_runner.py:77} INFO - Job 78: Subtask load_sftp_datadata_19.csv
[2023-06-09 15:22:21,987] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_19.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:22,852] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_19.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:22,960] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:23,229] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:23,448] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_19.csv, execution_date=20230609T152024, start_date=20230609T152220, end_date=20230609T152223
[2023-06-09 15:22:23,982] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:51,671] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_19.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:51,937] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_19.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:51,938] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:51,940] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:51,941] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:52,033] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_19.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:52,069] {standard_task_runner.py:52} INFO - Started process 986 to run task
[2023-06-09 16:52:52,089] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_19.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpw0hll1ee', '--error-file', '/tmp/tmpszs5p2bq']
[2023-06-09 16:52:52,121] {standard_task_runner.py:77} INFO - Job 42: Subtask load_sftp_datadata_19.csv
[2023-06-09 16:52:52,334] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_19.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:52,715] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_19.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:52,788] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:52,943] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:53,118] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_19.csv, execution_date=20230608T000000, start_date=20230609T165251, end_date=20230609T165253
[2023-06-09 16:52:54,114] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
