[2023-06-10 00:00:03,478] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_inc_load_pipeline.create_table scheduled__2023-06-09T00:00:00+00:00 [queued]>
[2023-06-10 00:00:03,528] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_inc_load_pipeline.create_table scheduled__2023-06-09T00:00:00+00:00 [queued]>
[2023-06-10 00:00:03,530] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-10 00:00:03,531] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-10 00:00:03,533] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-10 00:00:03,572] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): create_table> on 2023-06-09 00:00:00+00:00
[2023-06-10 00:00:03,581] {standard_task_runner.py:52} INFO - Started process 30849 to run task
[2023-06-10 00:00:03,589] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_inc_load_pipeline', 'create_table', 'scheduled__2023-06-09T00:00:00+00:00', '--job-id', '592', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_inc_load_pipeline.py', '--cfg-path', '/tmp/tmp79i8vpz7', '--error-file', '/tmp/tmpimakvx8v']
[2023-06-10 00:00:03,597] {standard_task_runner.py:77} INFO - Job 592: Subtask create_table
[2023-06-10 00:00:03,700] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_inc_load_pipeline.create_table scheduled__2023-06-09T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-10 00:00:03,829] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_inc_load_pipeline
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-09T00:00:00+00:00
[2023-06-10 00:00:03,877] {logging_mixin.py:109} INFO - Error creating table (psycopg2.errors.ActiveSqlTransaction) CREATE DATABASE cannot run inside a transaction block

[SQL: CREATE DATABASE lead_data_analytics;
CREATE TABLE IF NOT EXISTS leads_parquet
(
    "lead_UUID" TEXT NOT NULL,
    "phone_hash" TEXT NOT NULL,
    "email_hash" TEXT DEFAULT NULL,
    "index" INT DEFAULT NULL
);
]
(Background on this error at: http://sqlalche.me/e/13/2j85)
[2023-06-10 00:00:03,921] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-10 00:00:03,982] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_inc_load_pipeline, task_id=create_table, execution_date=20230609T000000, start_date=20230610T000003, end_date=20230610T000003
[2023-06-10 00:00:04,062] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
