[2023-06-09 15:08:44,824] {taskinstance.py:1029} INFO - Dependencies not met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_13.csv scheduled__2023-06-08T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state which is not a valid state for execution. The task must be cleared in order to be run.
[2023-06-09 15:08:45,026] {local_task_job.py:99} INFO - Task is not able to be run
[2023-06-09 15:22:29,103] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_13.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:29,376] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_13.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:29,389] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:29,393] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:29,396] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:29,572] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_13.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:29,603] {standard_task_runner.py:52} INFO - Started process 3573 to run task
[2023-06-09 15:22:29,631] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_13.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpab0nlmss', '--error-file', '/tmp/tmpv3akd4c2']
[2023-06-09 15:22:29,665] {standard_task_runner.py:77} INFO - Job 81: Subtask load_sftp_datadata_13.csv
[2023-06-09 15:22:30,127] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_13.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:30,535] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_13.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:30,653] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:30,816] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:31,020] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_13.csv, execution_date=20230609T152024, start_date=20230609T152229, end_date=20230609T152231
[2023-06-09 15:22:31,685] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:33,193] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_13.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:33,382] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_13.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:33,387] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:33,389] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:33,391] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:33,751] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_13.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:33,804] {standard_task_runner.py:52} INFO - Started process 838 to run task
[2023-06-09 16:52:33,904] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_13.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpp25kf60z', '--error-file', '/tmp/tmpcf86yeac']
[2023-06-09 16:52:33,980] {standard_task_runner.py:77} INFO - Job 30: Subtask load_sftp_datadata_13.csv
[2023-06-09 16:52:34,388] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_13.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:35,136] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_13.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:35,308] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:35,419] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:35,892] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_13.csv, execution_date=20230608T000000, start_date=20230609T165233, end_date=20230609T165235
[2023-06-09 16:52:39,400] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
